// Do not edit this file

#include "RouteLib.h"
#include "CarDispatcher.h"

static CarDispatcher * car_dispatcher = 0;


void RouteLib_Init(std::vector<IntersectionInfo> intersections, std::vector<RoadInfo> roads) {

  car_dispatcher = new CarDispatcher(intersections, roads);

}


void RouteLib_onTurn(std::vector<CarCtl> & cars_at_intersections, 
                      const std::vector<PassengerRequest> & passenger_requests) { 

  car_dispatcher->onTurn(cars_at_intersections, passenger_requests);

}

