// Do not edit this file

#ifndef TRANSPORTATION_TYPES_H_
#define TRANSPORTATION_TYPES_H_

//Information about cars traveling on roads

struct IntersectionInfo { 
  int intersection_id;
  int x_location;
  int y_location;  
};

struct RoadInfo { 
  int road_id;
  int src_intersection_id;
  int dst_intersection_id;
  int weight;
}; 

struct PassengerRequest { 
  int passenger_id;
  int src_intersection_id;
  int dst_intersection_id;
};

struct CarCtl {   
  int car_id;

  //Choose the next intersection you want to travel to by setting this to that intersection id.
  //You can only choose an intersection ID that is reachable from your current intersection 
  //via a single road. If you choose an invalid intersection, your program errors out. 
  int intersection_id; 

  //If passenger==-1, you are not carrying a passenger. 
  //To pick up a passenger, set this to the passenger id that you want to pick up.
  //Once a car picks up a passenger, it cannot pick up another passenger until it 
  //delivers the first passenger to their destination. If this is set to a passenger
  //not on your current intersection, or you try to pick up another passenger while you 
  //are already carrying one, the program errors out. 
  int passenger_id; 
};


#endif 


